In [47]:
import pandas as pd
import numpy as np

In [48]:
data = pd.read_csv('Absenteeism_preprocessed.csv')
data.head()

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  \
0         0         0         0         1                     289   
1         0         0         0         0                     118   
2         0         0         0         1                     179   
3         1         0         0         0                     279   
4         0         0         0         1                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the Week  
0         2     1                          4            7                1  
1         1     0                          0            7                1  
2         0     0                          2            7                2  
3         2     0                          4            7                3  
4         2     1                          2            7                3

In [49]:
targets = np.where(data['Absenteeism Time in Hours'] > 
                   data['Absenteeism Time in Hours'].median(), 1, 0)

In [50]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [51]:
data['Excessive Absenteeism'] = targets
data.head(10)

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  \
0         0         0         0         1                     289   
1         0         0         0         0                     118   
2         0         0         0         1                     179   
3         1         0         0         0                     279   
4         0         0         0         1                     289   
5         0         0         0         1                     179   
6         0         0         0         1                     361   
7         0         0         0         1                     260   
8         0         0         1         0                     155   
9         0         0         0         1                     235   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   
5                51   38                  239.554               31          0   
6                52   28                  239.554               27          0   
7                50   36                  239.554               23          0   
8                12   34                  239.554               25          0   
9                11   37                  239.554               29          1   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the Week  \
0         2     1                          4            7                1   
1         1     0                          0            7                1   
2         0     0                          2            7                2   
3         2     0                          4            7                3   
4         2     1                          2            7                3   
5         0     0                          2            7                4   
6         1     4                          8            7                4   
7         4     0                          4            7                4   
8         2     0                         40            7                0   
9         1     1                          8            7                0   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0  
5                      0  
6                      1  
7                      1  
8                      1  
9                      1

In [52]:
targets.sum() / targets.shape[0]

0.45571428571428574

In [53]:
data_with_target = data.drop(['Absenteeism Time in Hours'],axis=1)

In [54]:
data_with_target.head(10)

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  \
0         0         0         0         1                     289   
1         0         0         0         0                     118   
2         0         0         0         1                     179   
3         1         0         0         0                     279   
4         0         0         0         1                     289   
5         0         0         0         1                     179   
6         0         0         0         1                     361   
7         0         0         0         1                     260   
8         0         0         1         0                     155   
9         0         0         0         1                     235   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   
5                51   38                  239.554               31          0   
6                52   28                  239.554               27          0   
7                50   36                  239.554               23          0   
8                12   34                  239.554               25          0   
9                11   37                  239.554               29          1   

   Children  Pets  Month Value  Day of the Week  Excessive Absenteeism  
0         2     1            7                1                      1  
1         1     0            7                1                      0  
2         0     0            7                2                      0  
3         2     0            7                3                      1  
4         2     1            7                3                      0  
5         0     0            7                4                      0  
6         1     4            7                4                      1  
7         4     0            7                4                      1  
8         2     0            7                0                      1  
9         1     1            7                0                      1

In [55]:
data_with_target.shape

(700, 15)

In [56]:
data_with_target.iloc[:,:-1]

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  \
0           0         0         0         1                     289   
1           0         0         0         0                     118   
2           0         0         0         1                     179   
3           1         0         0         0                     279   
4           0         0         0         1                     289   
..        ...       ...       ...       ...                     ...   
695         1         0         0         0                     179   
696         1         0         0         0                     225   
697         1         0         0         0                     330   
698         0         0         0         1                     235   
699         0         0         0         1                     291   

     Distance to Work  Age  Daily Work Load Average  Body Mass Index  \
0                  36   33                  239.554               30   
1                  13   50                  239.554               31   
2                  51   38                  239.554               31   
3                   5   39                  239.554               24   
4                  36   33                  239.554               30   
..                ...  ...                      ...              ...   
695                22   40                  237.656               22   
696                26   28                  237.656               24   
697                16   28                  237.656               25   
698                16   32                  237.656               25   
699                31   40                  237.656               25   

     Education  Children  Pets  Month Value  Day of the Week  
0            0         2     1            7                1  
1            0         1     0            7                1  
2            0         0     0            7                2  
3            0         2     0            7                3  
4            0         2     1            7                3  
..         ...       ...   ...          ...              ...  
695          1         2     0            5                2  
696          0         1     2            5                2  
697          1         0     0            5                3  
698          1         0     0            5                3  
699          0         1     1            5                3  

[700 rows x 14 columns]

In [57]:
unscaled_inputs = data_with_target.iloc[:,:-1]

In [58]:
from sklearn.preprocessing import StandardScaler

absenteeism_scaler = StandardScaler()

In [59]:
absenteeism_scaler.fit(unscaled_inputs)

StandardScaler()

In [60]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [61]:
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ...,  0.26848661,
         0.18272635, -0.68370352],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
         0.18272635, -0.68370352],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
         0.18272635, -0.00772546],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ..., -0.58968976,
        -0.3882935 ,  0.66825259],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
        -0.3882935 ,  0.66825259],
       [-0.57735027, -0.09298136, -0.31448545, ...,  0.26848661,
        -0.3882935 ,  0.66825259]])

In [62]:
scaled_inputs.shape

(700, 14)

In [63]:
from sklearn.model_selection import train_test_split

In [64]:
train_test_split(scaled_inputs,targets)

[array([[-0.57735027, -0.09298136, -0.31448545, ...,  0.26848661,
          1.03925612, -0.00772546],
        [-0.57735027, -0.09298136, -0.31448545, ...,  1.12666297,
          1.61027597, -0.00772546],
        [-0.57735027, -0.09298136, -0.31448545, ...,  0.26848661,
          1.03925612,  1.34423065],
        ...,
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.58968976,
         -0.95931334, -0.00772546],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
          0.46823627,  0.66825259],
        [-0.57735027, -0.09298136, -0.31448545, ...,  1.12666297,
          0.18272635,  0.66825259]]),
 array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
         -0.67380342,  1.34423065],
        [-0.57735027, -0.09298136, -0.31448545, ...,  1.12666297,
          1.03925612,  2.69618675],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
         -0.95931334, -1.35968157],
        ...,
        [-0.57735027, -0.09298136, -0.31448545, ...,  

In [65]:
x_train , x_test , y_train , y_test = train_test_split(scaled_inputs,targets,train_size=.8 , random_state=20)

In [66]:
print(x_train.shape ,y_train.shape)

(560, 14) (560,)


In [67]:
print(x_test.shape ,y_test.shape)

(140, 14) (140,)


In [68]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [72]:
reg = LogisticRegression()

In [76]:
reg.fit(x_train,y_train)

LogisticRegression()

In [77]:
reg.score(x_train,y_train)

0.7839285714285714

In [78]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [79]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [80]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [83]:
np.sum((model_outputs == y_train))

439

In [82]:
model_outputs.shape[0]

560

In [84]:
np.sum((model_outputs == y_train))/model_outputs.shape[0]

0.7839285714285714

In [85]:
reg.intercept_

array([-0.22206736])

In [87]:
reg.coef_

array([[ 2.07601767,  0.33504757,  1.56162303,  1.32927434,  0.70639316,
        -0.03986811, -0.20089491, -0.00456366,  0.31933564, -0.135508  ,
         0.38172443, -0.3332426 ,  0.18793677, -0.07062253]])

In [88]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Month Value', 'Day of the Week'], dtype=object)

In [89]:
feature_name = unscaled_inputs.columns.values

In [90]:
summary_table = pd.DataFrame(columns=['Feature name'],data = feature_name)

summary_table['Coefficient'] =np.transpose(reg.coef_)

summary_table

Feature name  Coefficient
0                  Reason_1     2.076018
1                  Reason_2     0.335048
2                  Reason_3     1.561623
3                  Reason_4     1.329274
4    Transportation Expense     0.706393
5          Distance to Work    -0.039868
6                       Age    -0.200895
7   Daily Work Load Average    -0.004564
8           Body Mass Index     0.319336
9                 Education    -0.135508
10                 Children     0.381724
11                     Pets    -0.333243
12              Month Value     0.187937
13          Day of the Week    -0.070623

In [91]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                 Intercept    -0.222067
1                  Reason_1     2.076018
2                  Reason_2     0.335048
3                  Reason_3     1.561623
4                  Reason_4     1.329274
5    Transportation Expense     0.706393
6          Distance to Work    -0.039868
7                       Age    -0.200895
8   Daily Work Load Average    -0.004564
9           Body Mass Index     0.319336
10                Education    -0.135508
11                 Children     0.381724
12                     Pets    -0.333243
13              Month Value     0.187937
14          Day of the Week    -0.070623

In [92]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [93]:
summary_table

Feature name  Coefficient  Odds_ratio
0                 Intercept    -0.222067    0.800861
1                  Reason_1     2.076018    7.972656
2                  Reason_2     0.335048    1.398007
3                  Reason_3     1.561623    4.766551
4                  Reason_4     1.329274    3.778301
5    Transportation Expense     0.706393    2.026668
6          Distance to Work    -0.039868    0.960916
7                       Age    -0.200895    0.817998
8   Daily Work Load Average    -0.004564    0.995447
9           Body Mass Index     0.319336    1.376213
10                Education    -0.135508    0.873272
11                 Children     0.381724    1.464808
12                     Pets    -0.333243    0.716596
13              Month Value     0.187937    1.206757
14          Day of the Week    -0.070623    0.931814

In [94]:
summary_table.sort_values('Odds_ratio',ascending=False)

Feature name  Coefficient  Odds_ratio
1                  Reason_1     2.076018    7.972656
3                  Reason_3     1.561623    4.766551
4                  Reason_4     1.329274    3.778301
5    Transportation Expense     0.706393    2.026668
11                 Children     0.381724    1.464808
2                  Reason_2     0.335048    1.398007
9           Body Mass Index     0.319336    1.376213
13              Month Value     0.187937    1.206757
8   Daily Work Load Average    -0.004564    0.995447
6          Distance to Work    -0.039868    0.960916
14          Day of the Week    -0.070623    0.931814
10                Education    -0.135508    0.873272
7                       Age    -0.200895    0.817998
0                 Intercept    -0.222067    0.800861
12                     Pets    -0.333243    0.716596